# Editor Config
theme = "catppuccin_frappe"

[editor]
scrolloff = 8
mouse = true
middle-click-paste = true
scroll-lines = 3
shell = [ "sh", "-c" ]
line-number = "absolute"
cursorline = true
cursorcolumn = false
# gutters = [ "diagnostics", "spacer", "line-numbers", "spacer", "diff" ]
auto-completion = true
auto-format = true
auto-save = false
idle-timeout = 0
completion-trigger-len = 2
auto-info = true
true-color = true
rulers = []
bufferline = "always"
color-modes = true
auto-pairs = false

[editor.statusline]
left = [ "mode", "file-name", "separator", "diagnostics", ]
center = []
right = [
  "position", "separator", 
  "spacer", "position-percentage", "spacer", "separator", 
  "total-line-numbers", "separator", 
  "file-line-ending", "separator", 
  "file-type", ]
separator = "\ue0b3"
mode.normal = "NORMAL"
mode.select = "SELECT"
mode.insert = "INSERT"

[editor.lsp]
display-messages = false
auto-signature-help = true
display-signature-help-docs = true

# [editor.cursor-shape]
# insert = "underline"
# normal = "underline"
# select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = false
character = "│"
skip-levels = 0

# Key Remapping
[keys.normal]
"\\"."c"."o" = [ ":config-open", ]
"\\"."c"."r" = [ ":config-reload", ]
# "esc" = [ "keep_primary_selection", "normal_mode", ]
"C-s" = [ ":wa", ]
"C-q"."q" = [ ":xa", ]
"C-q"."b" = [ ":w", ":bc", ]
"C-q"."w" = [ ":w", "wclose", ]
"C-e" = [ "move_line_down", "scroll_down", ]
"C-y" = [ "move_line_up", "scroll_up", ]
"C-r" = [ "redo", ]
"C-j" = [ "move_line_down", "align_view_center", ]
"C-k" = [ "move_line_up", "align_view_center", ]
"C-a" = [ "select_all", "select_mode", ]
"$" = [ "goto_line_end", ]
"^" = [ "goto_first_nonwhitespace", ]
"0" = [ "goto_line_start", ]
"G" = [ "goto_last_line", ]
"M" = [ "goto_window_center", ]
"V" = [ "extend_to_line_bounds", "select_mode", ]
"D" = [
  "select_mode", "goto_line_end",
  "yank_main_selection_to_clipboard", "delete_selection", ]
"x" = [ "yank_main_selection_to_clipboard", "delete_selection", ]
"d"."d" = [
  "extend_to_line_bounds", "yank_main_selection_to_clipboard",
  "delete_selection", ]
"d"."i"."w" = [
  "move_char_right", "move_prev_word_start", "move_next_word_end",
  "yank_main_selection_to_clipboard", "delete_selection", ]
"y"."y" = [ "extend_to_line_bounds", "yank", "yank_main_selection_to_clipboard", ]
"y"."i"."w" = [
  "move_char_right", "move_prev_word_start", "move_next_word_end",
  "yank", "yank_main_selection_to_clipboard", ]
"s" = [
  "yank_main_selection_to_clipboard", "delete_selection",
  "insert_mode", ]
"c"."c" = [
  "extend_to_line_bounds", "yank_main_selection_to_clipboard",
  "delete_selection", "open_above", ]
"c"."i"."w" = [
  "move_char_right", "move_prev_word_start", "move_next_word_end",
  "yank_main_selection_to_clipboard", "delete_selection",
  "insert_mode", ]
"?" = [ "select_regex", ]
# "p" = [ "paste_clipboard_after", ]
# "P" = [ "paste_clipboard_before", ]

[keys.select]
"\\"."c"."o" = [ ":config-open", ]
"\\"."c"."r" = [ ":config-reload", ]
# "esc" = [ "keep_primary_selection", "normal_mode", ]
"tab" = [ "extend_to_line_bounds", "indent", ]
"S-tab" = [ "extend_to_line_bounds", "unindent", ]
"C-s" = [ ":wa", ]
"C-q"."q" = [ ":xa", ]
"C-q"."b" = [ ":w", ":bc", ]
"C-q"."w" = [ ":w", "wclose", ]
"C-e" = [ "move_line_down", "scroll_down", ]
"C-y" = [ "move_line_up", "scroll_up", ]
"C-r" = [ "redo", "normal_mode", ]
"C-j" = [
  "ensure_selections_forward", "extend_to_line_bounds",
  "extend_char_right", "extend_char_left", "delete_selection",
  "add_newline_below", "move_line_down", "replace_with_yanked",
  "select_mode", ]
"C-k" = [
  "ensure_selections_forward", "extend_to_line_bounds",
  "extend_char_right", "extend_char_left", "delete_selection",
  "move_line_up", "add_newline_above", "move_line_up",
  "replace_with_yanked", "select_mode", ]
"J" = [ "extend_visual_line_down", "extend_to_line_bounds", ]
"K" = [ "extend_visual_line_up", "extend_to_line_bounds", ]
"$" = [ "goto_line_end", ]
"^" = [ "goto_first_nonwhitespace", ]
"0" = [ "goto_line_start", ]
"G" = [ "goto_last_line", ]
"M" = [ "goto_window_center", ]
"V" = [ "extend_to_line_bounds", "select_mode", ]
"x" = [ "yank_main_selection_to_clipboard", "delete_selection", ]
"d" = [ "yank_main_selection_to_clipboard", "delete_selection", ]
"y" = [ "yank_main_selection_to_clipboard", "yank", "normal_mode", ]
"s" = [ "yank_main_selection_to_clipboard", "delete_selection", "insert_mode", ]
"c" = [ "yank_main_selection_to_clipboard", "delete_selection", "open_above", ]
"?" = [ "select_regex", ]
"p" = [ "paste_before", "delete_selection_noyank", ]
"P" = [ "paste_before", "yank_main_selection_to_clipboard", "delete_selection", ]

[keys.insert]
# "esc" = [ "keep_primary_selection", "normal_mode", ]

# If copy/paste doesn't work properly, install xclip.
