# Editor Config
theme = "catppuccin_macchiato"

[editor]
scrolloff = 6
mouse = true
middle-click-paste = true
scroll-lines = 5
shell = [ "sh", "-c" ]
line-number = "absolute"
cursorline = true
cursorcolumn = true
gutters = [ "diff", "line-numbers", "spacer", ]
auto-completion = true
auto-format = false
auto-save = true
idle-timeout = 0
completion-trigger-len = 2
auto-info = true
true-color = true
color-modes = true
auto-pairs = true
bufferline = "always"
text-width = 80
rulers = []

[editor.statusline]
left = [ "mode", "file-name", "separator", "spacer", "diagnostics", ]
center = []
right = [ "position", "separator",  "spacer", "position-percentage", "spacer", "separator", 
    "total-line-numbers", "separator",  "file-line-ending", "separator",  "file-type", ]
separator = ""
mode.normal = "NORMAL"
mode.select = "SELECT"
mode.insert = "INSERT"

[editor.lsp]
display-messages = false
auto-signature-help = true
display-signature-help-docs = true

[editor.cursor-shape]
insert = "underline"
normal = "underline"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = false
character = "▎"
skip-levels = 0

# Key Remapping
[keys.normal]
"\\"."c"."o" = [ ":config-open", ]
"\\"."c"."r" = [ ":config-reload", ]
# "esc" = [ "keep_primary_selection", ]
"esc" = [ "normal_mode", "move_char_left", "move_char_right", ]
"space"."q"."q" = [ ":xa", ]
"space"."q"."b" = [ ":w", ":bc", ]
"space"."q"."w" = [ ":w", "wclose", ]
"space"."q"."c" = [ ":qa!" ]
"C-e" = [ "scroll_down", ]
"C-y" = [ "scroll_up", ]
"C-j" = [ "scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down", ]
"C-k" = [ "scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up", ]
"C-r" = [ "redo", ]
"C-s" = [ ":wa", ]
"C-a" = [ "select_all", "select_mode", ]
"A-j" = [ "ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection",
    "add_newline_below", "move_line_down", "replace_with_yanked", ]
"A-k" = [ "ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection",
    "move_line_up", "add_newline_above", "move_line_up", "replace_with_yanked", ]
"A-h" = [ "unindent", ]
"A-l" = [ "indent", ]
"g"."g" = []
"g"."e" = []
"g"."k" = [ "goto_file_start", ]
"g"."j" = [ "goto_last_line", ]
"M" = [ "goto_window_center", ]
"V" = [ "extend_to_line_bounds", "select_mode", ]
"D" = [ "select_mode", "goto_line_end", "yank_main_selection_to_clipboard", "delete_selection", ]
"x" = [ "yank_main_selection_to_clipboard", "delete_selection", ]
"d"."d" = [ "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", ]
"d"."i"."w" = [ "move_char_right", "move_prev_word_start", "move_next_word_end", "yank_main_selection_to_clipboard", "delete_selection", ]
"y"."y" = [ "extend_to_line_bounds", "yank", "yank_main_selection_to_clipboard", ]
"y"."i"."w" = [ "move_char_right", "move_prev_word_start", "move_next_word_end", "yank", "yank_main_selection_to_clipboard", ]
"s" = [ "yank_main_selection_to_clipboard", "delete_selection", "insert_mode", ]
"c"."c" = [ "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "open_above", ]
"c"."i"."w" = [ "move_char_right", "move_prev_word_start", "move_next_word_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode", ]
"p"."p" = [ "paste_after", ]
"p"."P" = [ "paste_before", ]
"p"."i"."w" = [ "move_char_right", "move_prev_word_start", "move_next_word_end", "select_mode", "paste_before", "delete_selection_noyank", ]
"P"."p" = [ "paste_clipboard_after", ]
"P"."P" = [ "paste_clipboard_before", ]
"P"."i"."w" = [ "move_char_right", "move_prev_word_start", "move_next_word_end", "select_mode", "paste_clipboard_before", "delete_selection_noyank", ]
"?" = [ "select_regex", ]

[keys.select]
"\\"."c"."o" = [ ":config-open", ]
"\\"."c"."r" = [ ":config-reload", ]
"esc" = [ "normal_mode", "move_char_left", "move_char_right", ]
"space"."q"."q" = [ ":xa", ]
"space"."q"."b" = [ ":w", ":bc", ]
"space"."q"."w" = [ ":w", "wclose", ]
"space"."q"."c" = [ ":qa!" ]
"C-s" = [ ":wa", ]
"C-e" = [ "scroll_down", ]
"C-y" = [ "scroll_up", ]
"C-r" = [ "redo", "normal_mode", ]
"A-j" = [ "ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection",
    "add_newline_below", "move_line_down", "replace_with_yanked", "select_mode", ]
"A-k" = [ "ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection",
    "move_line_up", "add_newline_above", "move_line_up", "replace_with_yanked", "select_mode", ]
"A-h" = [ "unindent", "select_mode", ]
"A-l" = [ "indent", "select_mode", ]
"C-j" = [ "scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down", ]
"C-k" = [ "scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up", ]
"$" = [ "goto_line_end", ]
"^" = [ "goto_first_nonwhitespace", ]
"0" = [ "goto_line_start", ]
"g"."g" = []
"g"."e" = []
"g"."k" = [ "goto_file_start", ]
"g"."j" = [ "goto_last_line", ]
"M" = [ "goto_window_center", ]
"V" = [ "extend_to_line_bounds", "select_mode", ]
"x" = [ "yank_main_selection_to_clipboard", "delete_selection", ]
"d" = [ "yank_main_selection_to_clipboard", "delete_selection", ]
"y" = [ "yank_main_selection_to_clipboard", "yank", "normal_mode", ]
"s" = [ "yank_main_selection_to_clipboard", "delete_selection", "insert_mode", ]
"c" = [ "yank_main_selection_to_clipboard", "delete_selection", "open_above", ]
"?" = [ "select_regex", ]
"p" = [ "paste_before", "delete_selection_noyank", ]
"P" = [ "paste_before", "yank_main_selection_to_clipboard", "delete_selection", ]

[keys.insert]
"esc" = [ "normal_mode", "move_char_left", ]

# If copy/paste doesn't work properly, install xclip.
